#!/bin/bash

echo "Enter a number:"
read num

factorial=1

if ((num >= 0)); then
  for ((i = 2; i <= num; i++)); do
    factorial=$((factorial * i))
  done

  echo "The factorial of $num is $factorial"
else
  echo "Error: Please enter a non-negative integer."
fi
