#!/bin/bash

read -p "Enter a word: " word

reverse=""
length=${#word}

for (( i=$length-1; i>=0; i-- ))
do
    reverse="$reverse${word:$i:1}"
done

if [ "$word" = "$reverse" ]
then
    echo "The word is a palindrome."
else
    echo "The word is not a palindrome."
fi
